spring.application.name=WebTutorial
#spring.h2.console.enabled=true
#spring.datasource.url = jdbc:h2:file:/Users/devpathak/Documents/JAADUU
#spring.datasource.username = devDB
#spring.datasource.password = dev123

#jdbc:h2:file:/Users/devpathak/Documents/JAADUU/SF NOTES